"""Export and import REMORA configurations in various formats."""

from __future__ import annotations

import json
from collections import OrderedDict
from pathlib import Path
from typing import Any


def _format_shell_value(value: Any) -> str:
    """Format a value for shell script CLI override syntax."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, list):
        inner = " ".join(_format_shell_value(v) for v in value)
        return f'"{inner}"'
    if isinstance(value, float):
        abs_val = abs(value)
        if value != 0.0 and (abs_val < 1e-3 or abs_val >= 1e7):
            return f"{value:g}"
        return repr(value)
    return str(value)


def export_json(params: dict[str, Any], path: str | Path) -> None:
    """Export parameters to a JSON file."""
    Path(path).write_text(json.dumps(params, indent=2) + "\n")


def import_json(path: str | Path) -> OrderedDict[str, Any]:
    """Import parameters from a JSON file, preserving order."""
    return json.loads(Path(path).read_text(), object_pairs_hook=OrderedDict)


def export_shell_script(
    params: dict[str, Any],
    path: str | Path,
    *,
    executable: str = "./REMORA",
    input_file: str = "",
    num_procs: int = 1,
    mpi_command: str = "mpirun",
) -> None:
    """Export parameters as a shell script with CLI overrides.

    Generates a bash script that invokes the REMORA executable with all
    parameters passed as command-line overrides.
    """
    lines = [
        "#!/bin/bash",
        "# Generated by REMORA-GUI",
        f"# {len(params)} parameters",
        "",
    ]

    # Build command
    cmd_parts: list[str] = []
    if num_procs > 1:
        cmd_parts.append(f"{mpi_command} -n {num_procs}")
    cmd_parts.append(executable)

    if input_file:
        cmd_parts.append(input_file)

    # Add CLI overrides
    for key, value in params.items():
        cmd_parts.append(f"{key}={_format_shell_value(value)}")

    lines.append(" \\\n  ".join(cmd_parts))
    lines.append("")

    Path(path).write_text("\n".join(lines))
