"""Parameter sweep logic — generate combinatorial input files."""

from __future__ import annotations

import itertools
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from remora_gui.core.input_file import write_input_file


@dataclass
class SweepAxis:
    """One parameter to sweep over."""

    key: str
    start: float | None = None
    end: float | None = None
    step: float | None = None
    explicit: list[Any] | None = None

    def values(self) -> list[Any]:
        """Return the list of values for this axis."""
        if self.explicit is not None:
            return list(self.explicit)
        if self.start is not None and self.end is not None and self.step is not None:
            vals: list[float] = []
            v = self.start
            while v <= self.end + self.step * 1e-9:  # tolerance for float rounding
                if v > self.end + self.step * 0.5:
                    break
                vals.append(v)
                v += self.step
            return vals
        raise ValueError(
            f"SweepAxis '{self.key}' must specify either range (start/end/step) "
            f"or explicit values."
        )


@dataclass
class SweepConfig:
    """Configuration for a parameter sweep."""

    base_params: dict[str, Any]
    axes: list[SweepAxis]
    output_dir: Path
    name_template: str = ""
    header_comment: str = "Generated by REMORA-GUI parameter sweep"


def generate_sweep_combinations(axes: list[SweepAxis]) -> list[dict[str, Any]]:
    """Compute the Cartesian product of all sweep axes.

    Returns a list of dicts, each mapping parameter key → value for one run.
    """
    if not axes:
        return [{}]

    keys = [a.key for a in axes]
    value_lists = [a.values() for a in axes]

    return [
        dict(zip(keys, combo, strict=True))
        for combo in itertools.product(*value_lists)
    ]


def generate_sweep_inputs(
    config: SweepConfig,
) -> list[tuple[str, Path]]:
    """Generate input files for every combination in the sweep.

    Returns a list of ``(run_name, input_file_path)`` tuples.
    """
    combos = generate_sweep_combinations(config.axes)
    results: list[tuple[str, Path]] = []

    for i, overrides in enumerate(combos):
        # Build merged params
        merged = OrderedDict(config.base_params)
        merged.update(overrides)

        # Generate run name
        if config.name_template:
            name = config.name_template
            for key, val in overrides.items():
                name = name.replace(f"{{{key}}}", str(val))
        else:
            name = f"sweep_{i:03d}"

        # Write input file
        run_dir = config.output_dir / name
        run_dir.mkdir(parents=True, exist_ok=True)
        input_path = run_dir / "inputs"
        write_input_file(merged, input_path, header_comment=config.header_comment)
        results.append((name, input_path))

    return results
