"""Tests for core/project.py — Task 1.6."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from remora_gui.core.project import Project, SimulationRun

# ---------------------------------------------------------------------------
# SimulationRun basics
# ---------------------------------------------------------------------------


class TestSimulationRun:
    def test_default_status_is_draft(self) -> None:
        run = SimulationRun(
            id="abc",
            project_id="proj1",
            name="run_001",
            created_at=datetime.now(timezone.utc),
        )
        assert run.status == "draft"

    def test_optional_fields_default(self) -> None:
        run = SimulationRun(
            id="abc",
            project_id="proj1",
            name="run_001",
            created_at=datetime.now(timezone.utc),
        )
        assert run.started_at is None
        assert run.completed_at is None
        assert run.pid is None
        assert run.exit_code is None
        assert run.notes == ""
        assert run.tags == []


# ---------------------------------------------------------------------------
# Project.new
# ---------------------------------------------------------------------------


class TestProjectNew:
    def test_creates_directory_structure(self, tmp_path: Path) -> None:
        base = tmp_path / "my_project"
        proj = Project.new("Test Project", "A test.", str(base))

        assert base.is_dir()
        assert (base / "runs").is_dir()
        assert (base / "templates").is_dir()
        assert (base / "project.json").is_file()
        assert proj.name == "Test Project"
        assert proj.description == "A test."


# ---------------------------------------------------------------------------
# Save / Load round-trip
# ---------------------------------------------------------------------------


class TestSaveLoad:
    def test_round_trip(self, tmp_path: Path) -> None:
        base = tmp_path / "proj"
        original = Project.new("Round Trip", "Testing persistence.", str(base))

        loaded = Project.load(base)
        assert loaded.id == original.id
        assert loaded.name == original.name
        assert loaded.description == original.description
        assert loaded.base_directory == original.base_directory

    def test_datetime_survives_round_trip(self, tmp_path: Path) -> None:
        base = tmp_path / "proj"
        original = Project.new("DT Test", "Datetime check.", str(base))

        loaded = Project.load(base)
        # Datetimes should be close (save updates updated_at)
        assert isinstance(loaded.created_at, datetime)
        assert isinstance(loaded.updated_at, datetime)
        assert loaded.created_at == original.created_at

    def test_load_from_json_path(self, tmp_path: Path) -> None:
        base = tmp_path / "proj"
        Project.new("Path Test", "Load by file.", str(base))

        loaded = Project.load(base / "project.json")
        assert loaded.name == "Path Test"

    def test_round_trip_with_run(self, tmp_path: Path) -> None:
        base = tmp_path / "proj"
        proj = Project.new("With Run", "Has a run.", str(base))
        proj.create_run("run_001", {"remora.max_step": 10})
        proj.save()

        loaded = Project.load(base)
        assert len(loaded.runs) == 1
        assert loaded.runs[0].name == "run_001"
        assert loaded.runs[0].input_parameters == {"remora.max_step": 10}
        assert loaded.runs[0].status == "draft"


# ---------------------------------------------------------------------------
# create_run
# ---------------------------------------------------------------------------


class TestCreateRun:
    def test_creates_run_directory_and_input_file(self, tmp_path: Path) -> None:
        base = tmp_path / "proj"
        proj = Project.new("Run Test", "Test create_run.", str(base))

        run = proj.create_run("run_001", {"remora.max_step": 50, "remora.v": 1})

        run_dir = base / "runs" / "run_001"
        assert run_dir.is_dir()
        assert (run_dir / "inputs").is_file()
        assert run.name == "run_001"
        assert run.project_id == proj.id
        assert run.status == "draft"
        assert run.input_parameters["remora.max_step"] == 50

    def test_input_file_has_header(self, tmp_path: Path) -> None:
        base = tmp_path / "proj"
        proj = Project.new("Header", "Check header.", str(base))
        proj.create_run("run_002", {"remora.v": 0})

        content = (base / "runs" / "run_002" / "inputs").read_text()
        assert "Generated by REMORA-GUI" in content

    def test_run_appended_to_project(self, tmp_path: Path) -> None:
        base = tmp_path / "proj"
        proj = Project.new("Append", "Check list.", str(base))
        proj.create_run("r1", {"remora.v": 0})
        proj.create_run("r2", {"remora.v": 1})
        assert len(proj.runs) == 2
        assert proj.runs[0].name == "r1"
        assert proj.runs[1].name == "r2"
